# Generated by Django 5.1.1 on 2024-09-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskflow', '0002_alter_todo_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
